language: python

python:
  - "3.5"
  - "3.6"
  - "3.7"

jobs:
  include:
    - os: windows
      language: sh
      python: "3.7"
      before_install:
        - choco install python3 --params "/InstallDir:C:\\Python" --version 3.7.4
        - export PATH="/c/Python:/c/Python/Scripts:$PATH"
        - python -m pip install --upgrade pip wheel

branches:
  only:
  - master

cache: pip

install:
- pip install -r requirements.txt
- pip install -U pytest pytest-cov codecov
- if [[ $TRAVIS_PYTHON_VERSION != '3.5' ]]; then travis_retry pip install black; fi

script:
- pytest hyppo/
- if [[ $TRAVIS_PYTHON_VERSION != '3.5' ]]; then black --check --diff ./mgc; fi

after_success:
- codecov

notifications:
- email: false