version: 2.1

jobs:
  build-python:
    # parameters:
    #   name:
    #     type: string
    docker:
      - image: cimg/python:<< parameters.name >>
    steps:
      - checkout
      - restore_cache:
          key: v1-<< parameters.name >>-min-dependency-cache-{{ checksum "dev-requirements.txt" }}
      - run:
          name: install python dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r dev-requirements.txt
      - save_cache:
          key: v1-<< parameters.name >>-min-dependency-cache-{{ checksum "dev-requirements.txt" }}
          paths:
            - "venv"
      - run:
          name: test if package installs
          command: |
            . venv/bin/activate
            python3 setup.py install
  test-module:
    # parameters:
    #   name:
    #     type: string
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - restore_cache:
          key: v1-3.8-dependency-cache-{{ checksum "dev-requirements.txt" }}
      - run:
          name: install python dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r dev-requirements.txt
            pip install -e .
      - save_cache:
          key: v1-3.8-dependency-cache-{{ checksum "dev-requirements.txt" }}
          paths:
            - "venv"
      - run:
          name: run code linting
          command: |
            . venv/bin/activate
            black --check --diff ./hyppo/<< parameters.name >>
      - run:
          name: run tests and coverage
          command: |
            . venv/bin/activate
            pytest hyppo/<< parameters.name >>
            codecov
      - store_artifacts:
          path: htmlcov/
  deploy:
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - restore_cache:
          key: v1-3.8-dependency-cache-{{ checksum "dev-requirements.txt" }}
      - run:
          name: install python dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r dev-requirements.txt
            pip install -e .
      - save_cache:
          key: v1-3.8-dependency-cache-{{ checksum "dev-requirements.txt" }}
          paths:
            - "venv"
      - run:
          name: verify git tag vs. version
          command: |
            python3 -m venv venv
            . venv/bin/activate
            python setup.py verify
      - run:
          name: init .pypirc
          command: |
            echo -e "[pypi]" >> ~/.pypirc
            echo -e "username = $PYPI_USERNAME" >> ~/.pypirc
            echo -e "password = $PYPI_PASSWORD" >> ~/.pypirc
      - run:
          name: create packages
          command: |
            python setup.py sdist
      - run:
          name: upload to pypi
          command: |
            . venv/bin/activate
            twine upload dist/*

workflows:
  build-test-deploy:
    jobs:
      - build-python:
          name: "3.6"
      - build-python:
          name: "3.7"
      - build-python:
          name: "3.8"
      - test-module:
          name: "independence"
          requires:
            - "3.6"
            - "3.7"
            - "3.8"
      - test-module:
          name: "ksample"
          requires:
            - "3.6"
            - "3.7"
            - "3.8"
      - test-module:
          name: "time_series"
          requires:
            - "3.6"
            - "3.7"
            - "3.8"
      - test-module:
          name: "discrim"
          requires:
            - "3.6"
            - "3.7"
            - "3.8"
      - test-module:
          name: "tools"
          requires:
            - "3.6"
            - "3.7"
            - "3.8"
      - deploy:
          requires:
            - "independence"
            - "ksample"
            - "time_series"
            - "discrim"
            - "tools"
          filters:
            tags:
              only: /[0-9]+(\.[0-9]+)*/
            branches:
              ignore: /.*/