version: 2.1

orbs:
  python: circleci/python@1.2
  codecov: codecov/codecov@1.1.3

workflows:
  build_and_deploy:
    jobs:
      # - build:
      #     filters:
      #       tags:
      #         only: /.*/
      - test-python-install:
          version: "3.6"
          # requires:
          #   - build
      - test-python-install:
          version: "3.7"
          # requires:
          #   - build
      - test-python-install:
          version: "3.8"
          # requires:
          #   - build
      - deploy:
          # requires:
          #   - build
          filters:
            tags:
              only: /[0-9]+(\.[0-9]+)*/
            branches:
              ignore: /.*/

jobs:
  # build:
  #   docker:
  #     - image: cimg/python:3.8
  #   steps:
  #     - checkout
  #     - restore_cache:
  #         key: v1-dependency-cache-{{ checksum "setup.py" }}
  #     - run:
  #         name: install python dependencies
  #         command: |
  #           python3 -m venv venv
  #           . venv/bin/activate
  #           pip install pytest pytest-cov black coverage twine codecov
  #           pip install -r requirements.txt
  #           pip install -e .
  #     - save_cache:
  #         key: v1-dependency-cache-{{ checksum "setup.py" }}
  #         paths:
  #           - "venv"
  #     - run:
  #         name: run tests
  #         command: |
  #           . venv/bin/activate 
  #           pytest hyppo/
  #           coverage html
  #           codecov
  #     - store_artifacts:
  #         path: htmlcov/
  test-python-install:
    parameters:
      version:
        type: string
        default: latest
    docker:
      - image: cimg/python:<< parameters.version >>
    steps:
      - checkout
      - restore_cache:
          key: v1-dependency-cache-{{ checksum "setup.py" }}
      - run:
          name: install python dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install pytest pytest-cov black coverage twine codecov
            pip install -r requirements.txt
            pip install -e .
      - save_cache:
          key: v1-dependency-cache-{{ checksum "setup.py" }}
          paths:
            - "venv"
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            pytest hyppo/
            coverage html
            codecov
      - store_artifacts:
          path: htmlcov/
      - run:
          name: Smoke Test Install
          command: |
            python --version
            sudo pip3 install hyppo
  integration:
    docker:
      - image: cimg/python:3.8
    steps:
      - run: echo "It works!"
  deploy:
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - restore_cache:
          key: v1-dependency-cache-{{ checksum "setup.py" }}
      - run:
          name: install python dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install pytest pytest-cov black coverage twine codecov
            pip install -r requirements.txt
            pip install -e .
      - save_cache:
          key: v1-dependency-cache-{{ checksum "setup.py" }}
          paths:
            - "venv"
      - run:
          name: verify git tag vs. version
          command: |
            python3 -m venv venv
            . venv/bin/activate
            python setup.py verify
      - run:
          name: init .pypirc
          command: |
            echo -e "[pypi]" >> ~/.pypirc
            echo -e "username = $PYPI_USERNAME" >> ~/.pypirc
            echo -e "password = $PYPI_PASSWORD" >> ~/.pypirc
      - run:
          name: create packages
          command: |
            python setup.py sdist
      - run:
          name: upload to pypi
          command: |
            . venv/bin/activate
            twine upload dist/*
