version: 2.1

workflows:
  build-test-deploy:
    jobs:
      - build-python:
          version: "3.6"
      - build-python:
          version: "3.7"
      - build-python:
          version: "3.8"
      - test-module:
          module: "independence"
          requires:
            - build-python
      - test-module:
          module: "ksample"
          requires:
            - build-python
      - test-module:
          module: "time_series"
          requires:
            - build-python
      - test-module:
          module: "discrim"
          requires:
            - build-python
      - test-module:
          module: "tools"
          requires:
            - build-python
      - deploy:
          requires:
            - test-module
          filters:
            tags:
              only: /[0-9]+(\.[0-9]+)*/
            branches:
              ignore: /.*/

jobs:
  build-python:
    parameters:
      version:
        type: string
    docker:
      - image: cimg/python:<< parameters.version >>
    steps:
      - checkout
      - restore_cache:
          key: v1-<< parameters.version >>-min-dependency-cache-{{ checksum "dev-requirements.txt" }}
      - run:
          name: install python dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r dev-requirements.txt
      - save_cache:
          key: v1-<< parameters.version >>-min-dependency-cache-{{ checksum "dev-requirements.txt" }}
          paths:
            - "venv"
      - run:
          name: test if package installs
          command: |
            . venv/bin/activate
            python3 setup.py install
  test-module:
    parameters:
      module:
        type: string
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - restore_cache:
          key: v1-3.8-dependency-cache-{{ checksum "dev-requirements.txt" }}
      - run:
          name: install python dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r dev-requirements.txt
            pip install -e .
      - save_cache:
          key: v1-3.8-dependency-cache-{{ checksum "dev-requirements.txt" }}
          paths:
            - "venv"
      - run:
          name: run code linting
          command: |
            . venv/bin/activate
            black --check --diff ./hyppo/<< parameters.module >>
      - run:
          name: run tests and coverage
          command: |
            . venv/bin/activate
            pytest hyppo/<< parameters.module >>
            codecov
      - store_artifacts:
          path: htmlcov/
  deploy:
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - restore_cache:
          key: v1-3.8-dependency-cache-{{ checksum "dev-requirements.txt" }}
      - run:
          name: install python dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r dev-requirements.txt
            pip install -e .
      - save_cache:
          key: v1-3.8-dependency-cache-{{ checksum "dev-requirements.txt" }}
          paths:
            - "venv"
      - run:
          name: verify git tag vs. version
          command: |
            python3 -m venv venv
            . venv/bin/activate
            python setup.py verify
      - run:
          name: init .pypirc
          command: |
            echo -e "[pypi]" >> ~/.pypirc
            echo -e "username = $PYPI_USERNAME" >> ~/.pypirc
            echo -e "password = $PYPI_PASSWORD" >> ~/.pypirc
      - run:
          name: create packages
          command: |
            python setup.py sdist
      - run:
          name: upload to pypi
          command: |
            . venv/bin/activate
            twine upload dist/*